export const LENGTH_UNIT = [
  { name: 'm', value: 'm' },
  { name: 'cm', value: 'cm' },
  { name: 'mm', value: 'mm' },
  { name: 'km', value: 'km' },
  { name: 'feet', value: 'feet' },
  { name: 'inches', value: 'inches' },
  { name: 'yards', value: 'yards' },
  { name: 'miles', value: 'miles' },
  { name: 'nautical miles', value: 'nautical miles' },
];

export const MASS_UNIT = [
  { name: 'g', value: 'g' },
  { name: 'mg', value: 'mg' },
  { name: 'kg', value: 'kg' },
  { name: 'tonne', value: 'tonne' },
  { name: 'pound', value: 'pound' },
  { name: 'ounce', value: 'ounce' },
];
export const TIME_UNIT = [
  // { name: 'µs', value: 'µs' },
  { name: 'ms', value: 'ms' },
  { name: 'seconds', value: 'seconds' },
  { name: 'minutes', value: 'minutes' },
  { name: 'hours', value: 'hours' },
  { name: 'days', value: 'days' },
  { name: 'weeks', value: 'weeks' },
  { name: 'years', value: 'years' },
];

export const ANGLE_UNIT = [
  { name: 'deg', value: 'deg' },
  { name: 'rad', value: 'rad' },
  { name: 'turn', value: 'turn' },
  { name: 'grad', value: 'grad' },
];

export const TEMPERATURE_UNIT = [
  { name: 'celsius', value: 'celsius' },
  { name: 'fahrenheit', value: 'fahrenheit' },
  { name: 'kelvin', value: 'kelvin' },
];

export const UNIT = [
  { name: 'TIME_UNIT', value: 'TIME_UNIT' },
  { name: 'LENGTH_UNIT', value: 'LENGTH_UNIT' },
  { name: 'MASS_UNIT', value: 'MASS_UNIT' },
  { name: 'TEMPERATURE_UNIT', value: 'TEMPERATURE_UNIT' },
  { name: 'ANGLE_UNIT', value: 'ANGLE_UNIT' },
];

export const UNITMATCH = [
  // { name: "微秒", type: 'TIME_UNIT', value: 'µs' },
  { name: "毫秒", type: 'TIME_UNIT', value: 'ms' },
  { name: "秒", type: 'TIME_UNIT', value: 'seconds' },
  { name: "分钟", type: 'TIME_UNIT', value: 'minutes' },
  { name: "小时", type: 'TIME_UNIT', value: 'hours' },
  { name: "天", type: 'TIME_UNIT', value: 'days' },
  { name: "周", type: 'TIME_UNIT', value: 'weeks' },
  { name: "年", type: 'TIME_UNIT', value: 'years' },
  { name: "米", type: 'LENGTH_UNIT', value: 'm' },
  { name: "厘米", type: 'LENGTH_UNIT', value: 'cm' },
  { name: "毫米", type: 'LENGTH_UNIT', value: 'mm' },
  { name: "千米", type: 'LENGTH_UNIT', value: 'km' },
  { name: "英寸", type: 'LENGTH_UNIT', value: 'feet' },
  { name: "英尺", type: 'LENGTH_UNIT', value: 'inches' },
  { name: "码", type: 'LENGTH_UNIT', value: 'yards' },
  { name: "英里", type: 'LENGTH_UNIT', value: 'miles' },
  { name: "海里", type: 'LENGTH_UNIT', value: 'nautical miles' },
  { name: "克", type: 'MASS_UNIT', value: 'g' },
  { name: "毫克", type: 'MASS_UNIT', value: 'mg' },
  { name: "千克", type: 'MASS_UNIT', value: 'kg' },
  { name: "吨", type: 'MASS_UNIT', value: 'tonne' },
  { name: "磅", type: 'MASS_UNIT', value: 'pound' },
  { name: "盎司", type: 'MASS_UNIT', value: 'ounce' },
  { name: "角度", type: 'ANGLE_UNIT', value: 'deg' },
  { name: "弧度", type: 'ANGLE_UNIT', value: 'rad' },
  { name: "圈", type: 'ANGLE_UNIT', value: 'turn' },
  { name: "梯度", type: 'ANGLE_UNIT', value: 'grad' },
  { name: "摄氏度", type: 'TEMPERATURE_UNIT', value: 'celsius' },
  { name: "华氏度", type: 'TEMPERATURE_UNIT', value: 'fahrenheit' },
  { name: "开氏度", type: 'TEMPERATURE_UNIT', value: 'kelvin' },
  // { name: "µs", type: 'TIME_UNIT', value: 'µs' },
  { name: "ms", type: 'TIME_UNIT', value: 'ms' },
  { name: "seconds", type: 'TIME_UNIT', value: 'seconds' },
  { name: "minutes", type: 'TIME_UNIT', value: 'minutes' },
  { name: "hours", type: 'TIME_UNIT', value: 'hours' },
  { name: "days", type: 'TIME_UNIT', value: 'days' },
  { name: "weeks", type: 'TIME_UNIT', value: 'weeks' },
  { name: "years", type: 'TIME_UNIT', value: 'years' },
  { name: "m", type: 'LENGTH_UNIT', value: 'm' },
  { name: "cm", type: 'LENGTH_UNIT', value: 'cm' },
  { name: "mm", type: 'LENGTH_UNIT', value: 'mm' },
  { name: "km", type: 'LENGTH_UNIT', value: 'km' },
  { name: "ft", type: 'LENGTH_UNIT', value: 'feet' },
  { name: "in", type: 'LENGTH_UNIT', value: 'inches' },
  { name: "yd", type: 'LENGTH_UNIT', value: 'yards' },
  { name: "mi", type: 'LENGTH_UNIT', value: 'miles' },
  { name: "nmi", type: 'LENGTH_UNIT', value: 'nautical miles' },
  { name: "g", type: 'MASS_UNIT', value: 'g' },
  { name: "mg", type: 'MASS_UNIT', value: 'mg' },
  { name: "kg", type: 'MASS_UNIT', value: 'kg' },
  { name: "t", type: 'MASS_UNIT', value: 'tonne' },
  { name: "lb", type: 'MASS_UNIT', value: 'pound' },
  { name: "oz", type: 'MASS_UNIT', value: 'ounce' },
  { name: "deg", type: 'ANGLE_UNIT', value: 'deg' },
  { name: "rad", type: 'ANGLE_UNIT', value: 'rad' },
  { name: "turn", type: 'ANGLE_UNIT', value: 'turn' },
  { name: "grad", type: 'ANGLE_UNIT', value: 'grad' },
  { name: "C", type: 'TEMPERATURE_UNIT', value: 'celsius' },
  { name: "F", type: 'TEMPERATURE_UNIT', value: 'fahrenheit' },
  { name: "K", type: 'TEMPERATURE_UNIT', value: 'kelvin' },
];

  // "ns":"纳秒",
  // "µs":"微秒",
  // "ms":"毫秒",
  // "seconds":"秒",
  // "minutes":"分钟",
  // "hours":"小时",
  // "days":"天",
  // "weeks":"周",
  // "years":"年",
  // "m":"米",
  // "cm":"厘米",
  // "mm":"毫米",
  // "km":"千米",
  // "feet":"英寸",
  // "inches":"英尺",
  // "yards":"码",
  // "miles":"英里",
  // "nautical miles":"海里",
  // "g":"克",
  // "mg":"毫克",
  // "kg":"千克",
  // "tonne":"吨",
  // "pound":"磅",
  // "ounce":"盎司",
  // "deg":"角度",
  // "rad":"弧度",
  // "turn":"圈",
  // "grad":"梯度",
  // "celsius":"摄氏度(C)",
  // "fahrenheit":"华氏度(F)",
  // "kelvin":"开氏度(K)",
  // "rankine": "兰氏度(R)"

// export const UNITS = [
//   { name: 'm', value: 'm', unit_type: 'LENGTH_UNIT' },
//   { name: 'cm', value: 'cm', unit_type: 'LENGTH_UNIT' },
//   { name: 'mm', value: 'mm', unit_type: 'LENGTH_UNIT' },
//   { name: 'km', value: 'km', unit_type: 'LENGTH_UNIT' },
//   { name: 'kg', value: 'kg', unit_type: 'MASS_UNIT' },
// ];

// "m":"米",
// "cm":"厘米",
// "mm":"毫米",
// "km":"千米",
// "feet":"英寸"，
// "inches":"英尺"，
// "yards":"码",
// "miles":"英里",
// "nautical miles":"海里"

// "m":"m",
// "cm":"cm",
// "mm":"mm",
// "km":"km",
// "feet":"feet"，
// "inches":"inches"，
// "yards":"yards",
// "miles":"miles",
// "nautical miles":"nautical miles"

